### ISSUE TITLE
Code run failure

### ISSUE THREAD

**Issue by zqin1202** [shepardyan/Nested-Column-and-Constraint-Generation-nested-C-CG-for-Two-Stage-Robust-Optimization#1]
Why when I run the code, there is a bug shows that 
出错 InCCG (第 45 行)
    [KKTSystem, ~] = kkt(constrsSP{k}, sum(h.*z{k}, 'all') + sum(M.*w{k}), g);

出错 rosteringRO (第 30 行)
        [objIn, d] = InCCG(rc, x, dt, varargin{1});

出错 main (第 44 行)
[objRO, xRO, yRO] = rosteringRO(rostcase, dt, gamma);
 
 
 (×﹏×)求大神指点

**Comment by shepardyan** [comment]
您好！在我个人的电脑上运行是不报错的，因此，在您目前给出的报错信息中，我无法确定错误发生的原因。您是否可以提供更多的报错信息以及求解器、YALMIP等环境配置信息？
Hello! When running on my personal computer, no errors are reported. Therefore, based on the error information you have provided, I am unable to determine the cause of the error. Would you be able to provide more error logs as well as details about the solver, YALMIP, and other environmental configuration information?

**Comment by zqin1202** [comment]
冒昧打扰，感谢您百忙之中阅读评论并回复！下面是全部的报错信息，请问这种情况是我少安装了什么东西吗？
另外我想请教一下该如何学习嵌套CCG代码呢，目前除了您这边分享的代码，我暂时没找到其他的开源的嵌套CCG论文复现的matlab代码，在写自己的代码时感觉特别迷茫，不知道从何处下手，请问您有什么宝贵的意见吗

Warning: Solver not found (quadprog)
错误使用 lmi/kkt
KKT system can only be derived for LPs or QPs

出错 InCCG (第 45 行)
    [KKTSystem, ~] = kkt(constrsSP{k}, sum(h.*z{k}, 'all') + sum(M.*w{k}), g);

出错 rosteringRO (第 30 行)
        [objIn, d] = InCCG(rc, x, dt, varargin{1});

出错 main (第 44 行)
[objRO, xRO, yRO] = rosteringRO(rostcase, dt, gamma);

**Comment by shepardyan** [comment]
从报错信息上看，可能是由于您没有安装合适的求解器（例如Gurobi），导致YALMIP自动选择quadprog求解器，然后可能由于未安装MATLAB优化工具箱而报错。您可以先尝试正确配置Gurobi求解器。
算法实现方面，可能还需要回到Nested C&CG的原始论文，理解算法的几个步骤、内外层问题划分、双层规划的处理等。由于我的代码也只是我学习过程中的一些记录，不能保证正确，您可能还需要对照原始论文进行算法编写。

**Comment by zqin1202** [comment]
太感谢你的建议了，对我有非常大的帮助！可以问一下您装的是哪个版本的Gurobi吗？

**Comment by shepardyan** [comment]
我自己用的是11.0的Gurobi（最新版），现在申请学术版就可以直接下载这个版本。

**Comment by zqin1202** [comment]
好的，感谢大佬╰(✿´⌣`✿)╯♡！我确实没有安装工具箱，你说的MATLAB优化工具箱是指Optimization Toolbox这个吗，刚刚想一起问的，不小心把之前的问题删了

**Comment by shepardyan** [comment]
是的。不过一般的问题基本都可以采用YALMIP进行建模。随后，可以根据问题类型安装相应的求解器，不一定非要用Optimization Toolbox中提供的求解器。

**Comment by zqin1202** [comment]
好滴 感谢٩(๑˃̵ᴗ˂̵๑)۶ 祝您天天开心 生活愉快

**Comment by shepardyan** [comment]
感谢对项目的关注！欢迎继续对本项目提issue，共同学习。

**Comment by zqin1202** [comment]
大佬你的matlab是啥版本，Optimization Toolbox工具箱是在下载matlab的时候勾选吗
