### ISSUE TITLE
错误排查求助

### ISSUE THREAD

**Issue by zqin1202** [shepardyan/Nested-Column-and-Constraint-Generation-nested-C-CG-for-Two-Stage-Robust-Optimization#2]
您好！  
我最近在学习嵌套CCG算法，非常感谢您无私地分享了相关代码，您的复现代码对我的学习和实践帮助巨大！当在我编写自己的代码时遇到了一些问题。我的研究主题是关于选址路径规划，采用嵌套CCG算法，并使用MATLAB进行实现。目前我已经完成了确定性情况下的代码编写，但在最后一步计算优化结果时，目标函数显示为空。我怀疑这可能与约束条件有关，因此想请教您，在这种情况下应如何排查和修正约束中的错误呢？  
由于这个问题困扰了我很久，冒昧向您请教，如果有打扰，深感抱歉。再次感谢您的帮助！

**Comment by shepardyan** [comment]
您好！
如果是由于约束不可行造成的目标函数为空，可以采用求解器提供的 Irreducible Inconsistent Subsystem (IIS) 检测函数，找到相互冲突的几条约束。

**Comment by zqin1202** [comment]
您好！
抱歉冒昧地打扰到您，注意到您的复现代码在内层CCG中有yzw三个变量，并且yzw都是与目标函数直接相关的。其中y是0-1变量，zw是连续变量，在INCCG中，您将zw设为变量，并利用kkt转化有关zw的约束并添加到上层，y则取上一次InSP运行得到的值，您的思路清晰明了，对我理解嵌套CCG有巨大的帮助。

我在写自己的内层CCG代码的时候，发现出现了很多辅助决策变量（这些辅助决策变量中有0-1变量x1,x2,x3,rho和连续变量t），但是这些辅助决策变量没有直接出现在目标函数里，与目标函数相关的只有两个连续变量w,q。wq和辅助决策变量之间以及辅助决策变量自己之间有许多的约束。我想向您寻求意见，在请问这种情况下，kkt应该转化哪些约束条件更加合适呢，这些辅助决策变量是像复现代码里的y一样放到下层去解还是怎么处理更加合适呢

再次感谢您的无私帮助，祝您科研顺利，事事顺心

**Comment by shepardyan** [comment]
您好！
在我个人的理解中，kkt条件意在处理双层规划问题的求解，因此约束是否需要加入kkt条件中主要看对于上下层问题的划分，辅助决策变量也应该可以被划入上层/下层问题中。具体细节可能还需要您自己对建模进行分析。
祝顺利！
