### ISSUE TITLE
不确定场景直接影响内层的离散变量

### ISSUE THREAD

**Issue by zqin1202** [shepardyan/Nested-Column-and-Constraint-Generation-nested-C-CG-for-Two-Stage-Robust-Optimization#3]
您好！
抱歉打扰到您，我在运用嵌套CCG算法时遇到了一些困扰许久的问题，冒昧地想来寻求您的建议。
按照我的理解，在经典案例中，变化的场景为d，在内层主问题利用kkt变换得到最恶劣场景d之后，把d传到下层，此时把问题转化为一个确定性问题，在最内层计算出0-1变量和连续变量，把离散变量传回上层并添加约束，继续计算d。
但是我目前遇到了一个问题，不确定场景d直接影响的是离散变量，在内层离散变量确定的情况下，连续变量的值可以直接确定，在这种情况下当子问题返回离散变量的值之后，不管恶劣场景再怎么改变，连续变量的值都不会再发生改变，所以代码一直没有办法收敛。
请问在这种情况下我应该如何修改我的约束呢，或者您有曾经遇到过类似的情况吗？
感谢您耐心地看完这段话，祝您身体健康，工作学习一切顺利！

**Comment by shepardyan** [comment]
您好！
我理解您说的内层离散变量应该是指原论文中的离散形式的recourse变量。虽然不确定场景只影响了recourse变量，但内层的两个问题采用的是epigraph的形式，理应能够收敛。您描述的情况是：对于任意不确定场景d，都有最优recourse z保持不变，那么由于主问题一直增加cut，$\theta$最终会达到最劣场景所对应的子问题目标。
可能需要检查内层问题的收敛过程，看看在相同的u（主问题）和z（子问题）下，主问题和子问题能否达到同样的最优解。

**Comment by zqin1202** [comment]
感谢您的答复，应该是我内层主子问题拆分上面出现了问题，祝您圣诞节快乐，科研一切顺利！
